version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: dev/nginx/Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
        depends_on:
            - client
            - mailer

    client:
        build:
            context: client/docker/dev/nginx
        depends_on:
            - client-node

    client-node:
        build:
            context: client/docker/dev/node
        volumes:
            - ./client:/app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
        tty: true

    client-node-cli:
        build:
            context: client/docker/dev/node
        volumes:
            - ./client:/app

    api-postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

    mailer:
        image: mailhog/mailhog

volumes:
    api-postgres:
